before_install:
  - gem install bundler

matrix:
  include:
    - rvm: 1.9.2
      gemfile: gemfiles/Gemfile.1.9.2-
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.1.9.2+
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.1.9.2+
    - rvm: 2.1.10
      gemfile: gemfiles/Gemfile.1.9.2+
    - rvm: 2.2.6
      gemfile: gemfiles/Gemfile.1.9.2+
    - rvm: 2.3.3
      gemfile: gemfiles/Gemfile.1.9.2+
    - rvm: 2.4.0
      gemfile: gemfiles/Gemfile.1.9.2+
      env: COVERAGE=true
    - rvm: jruby
      gemfile: gemfiles/Gemfile.1.9.2+
