module Fog
  module Compute
    class XenServer
      module Models
        class Vif < Fog::Model
          # API Reference here:
          # http://docs.vmd.citrix.com/XenServer/6.2.0/1.0/en_gb/api/?c=VIF

          provider_class :VIF

          identity :reference

          attribute :allowed_operations
          attribute :current_operations
          attribute :currently_attached
          attribute :device
          attribute :ipv4_allowed
          attribute :ipv6_allowed
          attribute :locking_mode
          attribute :mac,                :aliases => :MAC
          attribute :mac_autogenerated,  :aliases => :MAC_autogenerated
          attribute :mtu,                :aliases => :MTU
          attribute :other_config
          attribute :qos_algorithm_params
          attribute :qos_algorithm_type
          attribute :qos_supported_algorithms
          attribute :runtime_properties
          attribute :status_code
          attribute :status_detail
          attribute :uuid

          has_one   :metrics,   :vifs_metrics
          has_one   :network,   :networks
          has_one   :vm,        :servers,          :aliases => :VM

          alias_method :server, :vm

          def save
            requires :server
            raise ArgumentError.new('network is required for this operation') \
            unless attributes[:__network]
            ref = service.create_vif attributes[:server], attributes[:__network]
            merge_attributes service.vifs.get(ref).attributes
          end
        end
      end
    end
  end
end