module Fog
  module Compute
    class XenServer
      module Models
        autoload :Blob, 'fog/compute/xen_server/models/blob'
        autoload :Blobs, 'fog/compute/xen_server/models/blobs'
        autoload :Bond, 'fog/compute/xen_server/models/bond'
        autoload :Bonds, 'fog/compute/xen_server/models/bonds'
        autoload :Console, 'fog/compute/xen_server/models/console'
        autoload :Consoles, 'fog/compute/xen_server/models/consoles'
        autoload :CrashDump, 'fog/compute/xen_server/models/crash_dump'
        autoload :CrashDumps, 'fog/compute/xen_server/models/crash_dumps'
        autoload :DrTask, 'fog/compute/xen_server/models/dr_task'
        autoload :DrTasks, 'fog/compute/xen_server/models/dr_tasks'
        autoload :GpuGroup, 'fog/compute/xen_server/models/gpu_group'
        autoload :GpuGroups, 'fog/compute/xen_server/models/gpu_groups'
        autoload :GuestMetrics, 'fog/compute/xen_server/models/guest_metrics'
        autoload :GuestsMetrics, 'fog/compute/xen_server/models/guests_metrics'
        autoload :Host, 'fog/compute/xen_server/models/host'
        autoload :HostCpu, 'fog/compute/xen_server/models/host_cpu'
        autoload :HostCpus, 'fog/compute/xen_server/models/host_cpus'
        autoload :HostCrashDump, 'fog/compute/xen_server/models/host_crash_dump'
        autoload :HostCrashDumps, 'fog/compute/xen_server/models/host_crash_dumps'
        autoload :HostMetrics, 'fog/compute/xen_server/models/host_metrics'
        autoload :HostPatch, 'fog/compute/xen_server/models/host_patch'
        autoload :HostPatchs, 'fog/compute/xen_server/models/host_patchs'
        autoload :Hosts, 'fog/compute/xen_server/models/hosts'
        autoload :HostsMetrics, 'fog/compute/xen_server/models/hosts_metrics'
        autoload :Model, 'fog/compute/xen_server/models/model'
        autoload :Network, 'fog/compute/xen_server/models/network'
        autoload :Networks, 'fog/compute/xen_server/models/networks'
        autoload :Pbd, 'fog/compute/xen_server/models/pbd'
        autoload :Pbds, 'fog/compute/xen_server/models/pbds'
        autoload :Pci, 'fog/compute/xen_server/models/pci'
        autoload :Pcis, 'fog/compute/xen_server/models/pcis'
        autoload :Pgpu, 'fog/compute/xen_server/models/pgpu'
        autoload :Pgpus, 'fog/compute/xen_server/models/pgpus'
        autoload :Pif, 'fog/compute/xen_server/models/pif'
        autoload :PifMetrics, 'fog/compute/xen_server/models/pif_metrics'
        autoload :Pifs, 'fog/compute/xen_server/models/pifs'
        autoload :PifsMetrics, 'fog/compute/xen_server/models/pifs_metrics'
        autoload :Pool, 'fog/compute/xen_server/models/pool'
        autoload :PoolPatch, 'fog/compute/xen_server/models/pool_patch'
        autoload :PoolPatchs, 'fog/compute/xen_server/models/pool_patchs'
        autoload :Pools, 'fog/compute/xen_server/models/pools'
        autoload :Role, 'fog/compute/xen_server/models/role'
        autoload :Roles, 'fog/compute/xen_server/models/roles'
        autoload :Server, 'fog/compute/xen_server/models/server'
        autoload :ServerAppliance, 'fog/compute/xen_server/models/server_appliance'
        autoload :ServerAppliances, 'fog/compute/xen_server/models/server_appliances'
        autoload :ServerMetrics, 'fog/compute/xen_server/models/server_metrics'
        autoload :ServersMetrics, 'fog/compute/xen_server/models/servers_metrics'
        autoload :Servers, 'fog/compute/xen_server/models/servers'
        autoload :StorageManager, 'fog/compute/xen_server/models/storage_manager'
        autoload :StorageManagers, 'fog/compute/xen_server/models/storage_managers'
        autoload :StorageRepositories, 'fog/compute/xen_server/models/storage_repositories'
        autoload :StorageRepository, 'fog/compute/xen_server/models/storage_repository'
        autoload :Tunnel, 'fog/compute/xen_server/models/tunnel'
        autoload :Tunnels, 'fog/compute/xen_server/models/tunnels'
        autoload :Vbd, 'fog/compute/xen_server/models/vbd'
        autoload :VbdMetrics, 'fog/compute/xen_server/models/vbd_metrics'
        autoload :Vbds, 'fog/compute/xen_server/models/vbds'
        autoload :VbdsMetrics, 'fog/compute/xen_server/models/vbds_metrics'
        autoload :Vdi, 'fog/compute/xen_server/models/vdi'
        autoload :Vdis, 'fog/compute/xen_server/models/vdis'
        autoload :Vif, 'fog/compute/xen_server/models/vif'
        autoload :VifMetrics, 'fog/compute/xen_server/models/vif_metrics'
        autoload :Vifs, 'fog/compute/xen_server/models/vifs'
        autoload :VifsMetrics, 'fog/compute/xen_server/models/vifs_metrics'
        autoload :Vlan, 'fog/compute/xen_server/models/vlan'
        autoload :Vlans, 'fog/compute/xen_server/models/vlans'
        autoload :Vmpp, 'fog/compute/xen_server/models/vmpp'
        autoload :Vmpps, 'fog/compute/xen_server/models/vmpps'
        autoload :Vtpm, 'fog/compute/xen_server/models/vtpm'
        autoload :Vtpms, 'fog/compute/xen_server/models/vtpms'
      end
    end
  end
end